- hosts: web
  sudo: yes

  tasks:
  - name: Ensure that Apache is installed
    yum: name={{server2}} state=present
  - name: Start Apache Services
    service: name={{server2}} enabled=yes state=started

